Make original api
neuneu39/CoachBot pull request #1
Opened 2018-06-24 18:10 UTC by neuneu39

@clonable-eden
簡単にですが、ユーザー側の入力に対して、自作api-serverをかえして値を返すapi-server.jsを作成しました。

2018-06-25 04:38 UTC, clonable-eden requested changes
コメントしましたmm

2018-06-25 04:38 UTC, clonable-eden commented on package.json
> +    "nodemon": "^1.17.5",
nodemonはdevDependenciesですね

2018-06-25 04:38 UTC, clonable-eden commented on src/server/route/answer.route.js
> +);
これだと、APIがポストされたメッセージを判断していない、と思うので、メッセージのマップを返すのではなく、こちら側（このAPI内）で入力したメッセージを判断するロジックを入れるべきですね。それがbotなので！

2018-06-25 04:38 UTC, clonable-eden commented on src/api-service.js
> +  getItems: () => {
getItemsという名前は適切ではないですね。botに入力内容をポストして返信を得る、という意味の名前が望ましいと思います。
例えば `getReply` とか。
↓のanswer.route.jsでの指摘内容も確認お願いします。

2018-06-26 09:46 UTC, neuneu39 commented on package.json
> +    "nodemon": "^1.17.5",
ありがとうございます。
こちら修正いたします。

2018-06-26 09:47 UTC, neuneu39 commented on src/api-service.js
> +  getItems: () => {
ご指摘ありがとうございます。
了解致しました。

2018-06-28 19:22 UTC, neuneu39 commented
@clonable-eden
自作api-server修正いたしました。
api用のserverはまだ、node app.jsの形で別で立ち上げる必要がありますが、apiのミニマムの機能は実装できているかなと思っております。一度ご確認お願いいたします。

入力したメッセージをサーバー側にPOSTするため、api-service.js内にpostMessageを作成しました。
入力したmessageをPOSTで./api/answerにおくり、responseを取得しています。

POSTを受け取る関数をanswer.route.jsにrouter.postとう形で作成しました。

```
入力 -> 出力
天気 -> いい天気ですね 
天気以外の文字 -> なんですか？
入力なし -> 入力してください
```

2018-06-29 10:19 UTC, Mitsuru53 commented
@neuneu39 さん
返答が帰ってくることが確認できました！
着実に前進してますね！

機能実装の方針については、 @clonable-eden さんと相談されたようなので、
別の面で、アドバイスさせていただきますね！

インデントがずれていたりと、少し読みにくかったりするかなと感じました
そこで、npm run lintコマンドをお試しくださいまし
コーディングが綺麗ではないところを指摘してくれるので便利ですよ！

2018-06-29 10:20 UTC, Mitsuru53 commented
ちなみにpackage.jsonのlintという箇所に--fixをつけると細かいところを自動的に修正してくれるのでよりおすすめです！

下の感じですね！
```
// --fixを追加した
  "lint": "eslint --fix --ext .js,.vue src test/unit test/e2e/specs",
```

2018-06-29 12:00 UTC, clonable-eden commented
ひとまず動くもの、という意味ではLGTMです！イメージ通りではないでしょうか。
ただ、コードフォーマットに加えて以下、

・テストコードを書く（api-service.js、Chat.vue）
・localhost:8080にアクセスしたときに`/Chat`へのリンクがない

も気になったので修正お願いします！

2018-07-02 10:41 UTC, neuneu39 commented
@clonable-eden さん
>localhost:8080にアクセスしたときに/Chatへのリンクがない
の対応
ループで回してLINE風の時系列表示の対応行いました。

テストコードについては、作成中にエラーが出たため、確認しております。

2018-07-02 12:06 UTC, clonable-eden commented
@neuneu39 ひとまずこのブランチはmasterにマージしてしまいましょう！

2018-07-02 12:12 UTC, merged