Fix eslintignore
neuneu39/CoachBot pull request #2
Opened 2018-07-02 13:59 UTC by neuneu39

@clonable-edenさん
・eslintignoreに/node_modules/追加してcheck対象から外しました。
・npm run lintで発生したエラーを解消しました。
・利用していない関数があったので削除しました。

2018-07-02 14:14 UTC, clonable-eden requested changes
@neuneu39 コメントしました

2018-07-02 14:14 UTC, clonable-eden commented on .eslintignore
> +
`/src/server/node_modules/` これも対象外にしないとダメですね。

2018-07-02 14:14 UTC, clonable-eden commented on src/server/app.js
> +// bocy-parser指定
x: bocy
o: body

2018-07-03 06:12 UTC, neuneu39 commented on .eslintignore
> +
そうでした。
ご指摘ありがとうございます。対応いたします。

2018-07-03 06:12 UTC, neuneu39 commented on src/server/app.js
> +// bocy-parser指定
修正いたします！

2018-07-03 12:56 UTC, neuneu39 commented
@clonable-edenさん
・eslintignoreにserver側の/node_modules/も追加しました。
・タイポ修正しました。

2018-07-03 13:33 UTC, clonable-eden commented
@neuneu39 LGTMです、マージしてください！

2018-07-03 13:33 UTC, clonable-eden approved these changes

2018-07-06 05:41 UTC, merged

2018-07-06 05:41 UTC, neuneu39 commented
@clonable-eden 
ご確認いただきありがとうございます。マージ致しました。